### PR TITLE
Removed webpack-bundle-tracker as there is no new version to correct …

### PR DESCRIPTION
**Pull request by garethmcc**
…error and use of package looks non-critical to running of application

### CODE REVIEW

**Comment by anapaulagomes** [comment]
I wasn't able to run the application without `webpack-bundle-tracker` in a brand new environment. If it is possible, could you update the instructions (README.md) please?

**Comment by ayr-ton** [comment]
@anapaulagomes Strange. I just removed everything and tried again and its working as expected. @macecchi is running thought the same issue. Maybe could we revert this PR?

**Comment by ayr-ton** [comment]
@garethmcc clues on why is this happening?

**Comment by garethmcc** [comment]
[This line](https://github.com/ayr-ton/kamu/blob/a5fcc876e7d169f340aac2e0970bc74d0ed92382/kamu/common_settings.py#L79) has a reference to the file generated by the removed module. If that line was removeable (which I am not sure) then it should all work. I cannot see any reference to it apart from there.

**Pull request merged**
